### ISSUE TITLE
Question: How to make a call to asterisk with auth

### ISSUE THREAD

**Issue by jzielke84** [SIPp/sipp#435]
Hi,

first of all I hope it's ok posting my question here rather than using the mailing list, because I find them hard to read.

My scenario is: I have an Asterisk Instance running and serving one account and one extension (00000). What I'm trying to do is building an XML scenario where sipp would log in (e.g. register), make a call to that extension where an announcement will be played, wait until silence (or a fixed definition of seconds), play a sound file back to it, wait another couple of seconds and hang up.

Pretty simple probably to realize but I've spend nearly 8 hours of using google and the docs but only ending up sipp saying "401 unauthorized". No matter if I set the authorization line, use csv with variables or hardcode them in the xml file itself. When I use XLite ad a reference it works perfectly fine.

I really don't have the time to dig myself deep into the SIP protocol, since I just want to use sipp as a mocking service. So probably you guys can help me out with a template that works that way (or at least works with the registration part).

Thanks in advance!

**Comment by jzielke84** [comment]
OK from what I've diagnosed so far, [field2] is being ignored from my csv in the authorization header.

my csv looks like:
```csv
SEQUENTIAL
bot;127.0.0.1:5060;[authentication username=bot password=botpass];
```

but the response is:
```yml
2019-11-07      12:06:48.858643 1573124808.858643: Aborting call on unexpected message for Call-Id '1-4035@127.0.1.1': while expecting '100' (index 4), received 'SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 127.0.1.1:5061;rport=5061;received=127.0.0.1;branch=z9hG4bK-4035-1-3
Call-ID: 1-4035@127.0.1.1
From: <sip:bot@127.0.0.1>;tag=1
To: <sip:bot@127.0.0.1>;tag=z9hG4bK-4035-1-3
CSeq: 2 REGISTER
WWW-Authenticate: Digest realm="asterisk",nonce="1573124808/d1061014a8dfdad393d9ebd5cd650a81",opaque="6e66969b6a07bb05",algorithm=md5,qop="auth"
Server: Asterisk PBX 16.2.1~dfsg-1+deb10u1
Content-Length:  0
```
